In [ ]:
import numpy as np

my_arr = np.arange(1_000_000)

my_list = list(range(1_000_000))

%time for _ in range(10): my_arr2 = my_arr * 2

%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

CPU times: user 7.31 ms, sys: 3.93 ms, total: 11.2 ms
Wall time: 11.5 ms
CPU times: user 364 ms, sys: 88.8 ms, total: 453 ms
Wall time: 459 ms


In [ ]:
data = np.array([[1.5, -0.1, 3], [2, 0.5, 1], [3, 0.2, 2]])
# 数组是元组的嵌套，数组内的元素必须是相同类型
# 数组的形状是一个元组，元组的长度就是数组的维度
data.shape

(3, 3)

In [4]:
data.dtype

dtype('float64')

In [5]:
data.size

9

In [6]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)

arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [7]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)

arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [8]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [10]:
np.empty((2, 3, 2)) 
# Create new arrays by allocating new memory, but do not populate with any values like ones and zeros

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(15).reshape(3, 5) # 定义一个3行5列的数组

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [13]:
np.random.randn(4, 4)

array([[ 0.55225618,  0.09405958,  0.84091356, -0.14646534],
       [ 1.13431171, -1.81129635, -0.26972513,  0.35351085],
       [-0.78621249,  0.4146926 , -0.53629788, -0.07888803],
       [-1.81946445,  0.51033517, -0.61839656, -0.32772592]])

In [14]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

arr1

array([1., 2., 3.])

In [15]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

arr2

array([1, 2, 3], dtype=int32)

In [16]:
float_arr = arr2.astype(np.float64)

float_arr

array([1., 2., 3.])

In [17]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [18]:
arr.astype(np.int32)
arr


array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [19]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.bytes_)

numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [20]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [21]:
numeric_strings
# Calling astype always creates a new array (a copy of the data)
# even if the new data type is the same as the old data type.

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

S4 是 string 的type code，每一种 type 都有对应的简写版本

In [22]:
int_array = np.arange(10)

calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

int_array.astype(calibers.dtype)
# You can also use another array’s dtype attribute:

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

### 数组的运算
数组非常重要，因为它使你能够对数据进行批量操作，而**无需编写任何 for 循环**。NumPy 用户将此称为 “向量化” 。大小相等的数组之间的任何算术运算都按元素进行：

In [23]:
arr = np.array([[1.,2.,3.],[4.,5.,6.]])
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [24]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [26]:
arr ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [27]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### 基础索引和切片 indexing and slicing
NumPy 数组索引是一个很深奥的话题，因为有很多方法可以用来选择数据子集或单个元素。

In [28]:
 arr = np.arange(10)
 arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
arr[5]

np.int64(5)

In [30]:
arr[0] # 取第一个元素

np.int64(0)

In [31]:
arr[5:8]
# 第六个元素到第八个元素

array([5, 6, 7])

In [32]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [33]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [34]:
arr_slice[1] = 12345
arr
# 在 Numpy中，数组的切片是引用，而不是复制
# 数组的切片是视图，而不是副本
# 修改arr_slice的值，会修改arr的值

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

如果你想要的是 ndarray 切片的副本而不是视图，则需要显式复制该数组，例如 arr[5:8].copy() 。正如你所见，pandas 也是这样工作的。
Numpy为了更高效地处理数据，因此与普通 python 不同，不允许频繁复制。

In [35]:
arr_copy = arr[5:8].copy()
arr_copy = 13
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

### Higher dimensional arrays

In [36]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[2]

array([7, 8, 9])

In [37]:
arr2d[0][2] # 0行2列

np.int64(3)

In [38]:
arr2d[0,2] # 0行2列
# 与上一段代码等价

np.int64(3)

In [39]:
arr3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [40]:
arr3d[1]

array([[5, 6],
       [7, 8]])

In [41]:
old_values = arr3d[1].copy()
arr3d[1] = 12
arr3d

array([[[ 1,  2],
        [ 3,  4]],

       [[12, 12],
        [12, 12]]])

In [42]:
arr3d[1] = old_values
arr3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [43]:
arr3d[1,1]

array([7, 8])

In [44]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [45]:
arr[1:6] 
# 索引第 2 到第 6 个元素
# 从1开始，到6结束，不包括6
# 索引从0开始

array([ 1,  2,  3,  4, 12])

In [46]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [49]:
lower_dim_slice = arr2d[1, :2]
lower_dim_slice

array([4, 5])

In [50]:
lower_dim_slice.shape

(2,)

In [51]:
arr2d[:2, 2:]

array([[3],
       [6]])

In [52]:
arr2d[:2,2]

array([3, 6])

In [53]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

### Boolean Indexing

In [54]:
names = np.array(["bob", "joe", "will", "bob", "will", "joe", "joe"])

data =  np.array([[4, 7], [0, 2], [-5, 6], [0, 12], [-1, 12], [7, 4], [2, -5]])

names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [55]:
data

array([[ 4,  7],
       [ 0,  2],
       [-5,  6],
       [ 0, 12],
       [-1, 12],
       [ 7,  4],
       [ 2, -5]])

In [56]:
names == 'bob'

array([ True, False, False,  True, False, False, False])

In [57]:
data[names == 'bob']

array([[ 4,  7],
       [ 0, 12]])

In [58]:
data[names == 'bob', 1:]

array([[ 7],
       [12]])

In [59]:
data[names == 'bob', 1]

array([ 7, 12])

In [60]:
~(names == 'bob')
# “～”语法是取布尔值的相反值，在复杂布尔值算法下，非常方便。

array([False,  True,  True, False,  True,  True,  True])

In [61]:
data[names != 'bob']

array([[ 0,  2],
       [-5,  6],
       [-1, 12],
       [ 7,  4],
       [ 2, -5]])

In [62]:
cond = names == 'bob'

data[~cond]

array([[ 0,  2],
       [-5,  6],
       [-1, 12],
       [ 7,  4],
       [ 2, -5]])

通过布尔索引从数组中选择数据并将结果分配给新变量始终会创建数据的副本，即使返回的数组没有改变。

Python 关键字 and 和 or 不适用于布尔数组。请使用 & （与）和 | （或）代替。

In [63]:
mask = (names == 'bob') | (names == 'will')
mask

array([ True, False,  True,  True,  True, False, False])

使用布尔数组设置值的方法

In [64]:
data[data < 0] = 0
data

array([[ 4,  7],
       [ 0,  2],
       [ 0,  6],
       [ 0, 12],
       [ 0, 12],
       [ 7,  4],
       [ 2,  0]])

In [65]:
data[:, 1] = 1
data

array([[4, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [0, 1],
       [7, 1],
       [2, 1]])

### fancy indexing
与普通索引的区别
- 普通索引 arr[1:3] 会选择连续的行（从索引1到索引2）
- 花式索引 arr[[4, 3, 0, 6]] 允许您选择任意行并按照您指定的顺序排列

In [66]:
arr = np.zeros((8,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [67]:
for i in range(8):
    arr[i] = i # 为数组赋值1-8
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [68]:
# 按特定顺序选择行的子集
arr[[4, 3, 0, 6]] # 双中括号 == 花式索引

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [69]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])